Added option for exceptions
lgarron/ugly-http-extension pull request #17
Opened 2017-06-13 20:12 UTC by magnuswatn

Hi,

I added the option for exceptions. It's simple and the GUI is rudimentary, but it works :-)

2017-06-13 20:54 UTC, lgarron commented
Thanks for implementing!

I haven't tried it yet, but the basic idea sounds fine. I'll leave comments on the code.

2017-06-13 20:58 UTC, lgarron commented on content.js
> +    var exceptions = items.exceptions.split(',')
However, I'm a little concerned about parsing an exception list on every page load. I don't think you can store `Set`s in `chrome.storage`, but could you store it as a map?

    {
      "bing.com": true
      "example.com": true
    }

2017-06-13 20:58 UTC, lgarron commented on content.js
> +    if (!exceptions.includes(window.location.host)) {
`host` can include an optional port. Could you use `hostname` instead?

2017-06-13 20:58 UTC, lgarron commented on options/options.html
> +          <input type="text" id="exceptions">
Could we make this a `textarea` with newlines between hosts?

2017-06-14 19:36 UTC, magnuswatn commented
Thanks for the feedback! I will have a look at this again tomorrow.

2017-07-24 16:12 UTC, magnuswatn commented
Sorry this took so long, time flew by... I had a go again, it would be great if you could take a look!

2017-07-25 22:33 UTC, lgarron requested changes
Thanks! I've left a few more comments about details.

2017-07-25 22:33 UTC, lgarron commented on options/options.js
> +        exceptionList.value += exception + '\n';
Does the trailing newline cause an empty entry when serializing, or is that avoided?

2017-07-25 22:33 UTC, lgarron commented on options/options.js
> +    exceptions: ""
(same as above)

2017-07-25 22:33 UTC, lgarron commented on content.js
> +    exceptions: ""
This should be `{}` now, right?

2017-07-26 18:34 UTC, magnuswatn commented on content.js
> +    exceptions: ""
You are, of course, absolutely correct. My bad. I have fixed this now.

2017-07-26 18:41 UTC, magnuswatn commented on options/options.js
> +        exceptionList.value += exception + '\n';
That is avoided by:
`if (item)` (on line 20)
An empty string will be false, and thus is not added.

2017-07-27 16:56 UTC, merged

2017-07-27 17:49 UTC, lgarron commented
Merged and released. Thanks!